legacyRedirect:
    enabled: true
    from: newplayer
    to: build
disableMVTP:
- newPlayer
connectDelay: 200
premiumVanish: true
themedbuildWorld: themedbuilds
syncStatistic: true
discordChannel: Global
database:
  dbName: development
  user: development
  password: development
  ip: localhost
  port: 3306
